#!/usr/bin/env Rscript

# ------------------------------------------------------------
# 08_plot_volcano.R
#
# Create volcano plot from DESeq2 results.
#
# Input:
#   DESeq2 results table generated by:
#   scripts/05_deseq2_differential_expression.R
#
# Expected columns:
#   gene_id
#   log2FoldChange
#   padj
#
# Usage:
#   Rscript scripts/08_plot_volcano.R \
#     results/deseq2/DESeq2_all_results.tsv \
#     results/figures/volcano_plots \
#     treatment_vs_control
#
# Output:
#   results/figures/volcano_plots/volcano_treatment_vs_control.pdf
# ------------------------------------------------------------

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggrepel)
  library(readr)
})

options(ggrepel.max.overlaps = Inf)

args <- commandArgs(trailingOnly = TRUE)

if (length(args) != 3) {
  stop(
    "Usage:\n",
    "Rscript scripts/08_plot_volcano.R ",
    "<deseq2_results.tsv> <output_dir> <analysis_name>\n\n",
    "Example:\n",
    "Rscript scripts/08_plot_volcano.R ",
    "results/deseq2/DESeq2_all_results.tsv ",
    "results/figures/volcano_plots ",
    "treatment_vs_control"
  )
}

res_file <- args[1]
output_dir <- args[2]
analysis_name <- args[3]

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

# ------------------------------------------------------------
# Parameters
# ------------------------------------------------------------

log2fc_cutoff <- 1
padj_cutoff <- 0.01
x_axis_limit <- 2

# ------------------------------------------------------------
# Read DESeq2 results
# ------------------------------------------------------------

de <- read.delim(
  res_file,
  header = TRUE,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

required_columns <- c("gene_id", "log2FoldChange", "padj")

missing_columns <- setdiff(required_columns, colnames(de))

if (length(missing_columns) > 0) {
  stop(
    "Missing required columns in DESeq2 results file: ",
    paste(missing_columns, collapse = ", ")
  )
}

# ------------------------------------------------------------
# Prepare data for plotting
# ------------------------------------------------------------

de <- de %>%
  mutate(
    log2FoldChange = as.numeric(log2FoldChange),
    padj = as.numeric(padj)
  ) %>%
  filter(!is.na(log2FoldChange), !is.na(padj)) %>%
  mutate(
    diffexpressed = case_when(
      log2FoldChange >= log2fc_cutoff & padj < padj_cutoff ~ "UP",
      log2FoldChange <= -log2fc_cutoff & padj < padj_cutoff ~ "DOWN",
      TRUE ~ "NO"
    ),
    diffexpressed = factor(
      diffexpressed,
      levels = c("UP", "DOWN", "NO")
    )
  )

# ------------------------------------------------------------
# Build legend labels with counts
# ------------------------------------------------------------

reg_counts <- as.data.frame(table(de$diffexpressed))
colnames(reg_counts) <- c("diffexpressed", "n")

label_map <- c(
  "UP" = "Upregulated",
  "DOWN" = "Downregulated",
  "NO" = "Not Significant"
)

reg_labels <- setNames(
  paste0(label_map[reg_counts$diffexpressed], " (", reg_counts$n, ")"),
  reg_counts$diffexpressed
)

# This keeps all legend categories visible, even if one has zero genes
dummy_levels <- data.frame(
  log2FoldChange = c(1, 1, 1),
  padj = c(1, 1, 1),
  diffexpressed = factor(
    c("UP", "DOWN", "NO"),
    levels = c("UP", "DOWN", "NO")
  )
)

# ------------------------------------------------------------
# Volcano plot
# ------------------------------------------------------------

volcano_plot <- ggplot(
  de,
  aes(
    x = log2FoldChange,
    y = -log10(padj),
    color = diffexpressed
  )
) +
  geom_point(alpha = 0.7) +
  geom_point(
    data = dummy_levels,
    aes(
      x = log2FoldChange,
      y = -log10(padj),
      color = diffexpressed
    )
  ) +
  geom_vline(
    xintercept = c(-log2fc_cutoff, log2fc_cutoff),
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_hline(
    yintercept = -log10(padj_cutoff),
    linetype = "dashed",
    linewidth = 0.4
  ) +
  scale_color_manual(
    values = c(
      "UP" = "coral1",
      "DOWN" = "cadetblue2",
      "NO" = "azure3"
    ),
    labels = reg_labels,
    drop = FALSE
  ) +
  coord_cartesian(
    xlim = c(-x_axis_limit, x_axis_limit)
  ) +
  labs(
    x = "log2 fold change",
    y = "-log10 adjusted p-value",
    color = "Sig. Differentially Expressed"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(
      color = "black",
      fill = NA,
      linewidth = 0.5
    ),
    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_line(color = "grey95"),
    legend.position = "top",
    legend.title = element_blank(),
    legend.direction = "horizontal",
    legend.text = element_text(size = 10),
    legend.spacing.x = unit(0.5, "cm")
  )

# ------------------------------------------------------------
# Save plot
# ------------------------------------------------------------

output_file <- file.path(
  output_dir,
  paste0("volcano_", analysis_name, ".pdf")
)

ggsave(
  filename = output_file,
  plot = volcano_plot,
  width = 6,
  height = 6
)

message("Volcano plot saved to: ", output_file)
